// All skill data lives here. Add, edit, or remove skills — push to deploy.

export const SKILLS = [
  {
    id: 1,
    slug: "strategy-consultant",
    name: "Strategy Consultant",
    author: "ChipAlexandru",
    description: "End-to-end strategy frameworks — market analysis, competitive positioning, strategic planning. Includes PESTEL, Porter's Five Forces, and value chain analysis.",
    long_description: "This skill turns Claude into a strategy consultant. When you ask about market entry, competitive positioning, or strategic planning, Claude applies proven frameworks and returns structured analysis — not generic advice.",
    repo_url: "https://github.com/ChipAlexandru/strategy-consultant",
    installs: 180,
    stars: 24,
    badge: "Editor's Pick",
    industries: ["cpg", "retail", "travel"],
    functions: ["strategy", "marketing"],
    use_cases: [
      { ask: "Analyse our competitive position in European travel retail", returns: "Porter's Five Forces analysis with market-specific data, key competitor mapping, and strategic recommendations" },
      { ask: "Build a market entry strategy for Southeast Asia", returns: "PESTEL framework applied to target market, entry mode comparison, risk assessment, and phased go-to-market plan" },
      { ask: "Review our 3-year strategic plan", returns: "Gap analysis against industry benchmarks, identification of strategic blind spots, and prioritised initiative roadmap" },
      { ask: "Compare build vs. buy for our data platform", returns: "Structured decision matrix with cost modelling, capability assessment, timeline comparison, and recommendation" },
    ],
  },
  {
    id: 2,
    slug: "retail-media-analyzer",
    name: "Retail Media Analyzer",
    author: "ChipAlexandru",
    description: "Retail media network performance across Amazon, Walmart, and Instacart. CPM/CPC benchmarks and media spend optimization.",
    long_description: "Gives Claude deep knowledge of retail media networks. Ask about campaign performance, budget allocation, or benchmarks and get analysis grounded in current CPM/CPC rates across major platforms.",
    repo_url: null,
    installs: 65,
    stars: 12,
    badge: null,
    industries: ["retail", "cpg"],
    functions: ["marketing", "data"],
    use_cases: [
      { ask: "How is our Amazon Sponsored Products campaign performing vs. category benchmarks?", returns: "Performance breakdown by ASIN with CPM/CPC comparison against category medians and optimisation recommendations" },
      { ask: "Reallocate our Q3 retail media budget across platforms", returns: "Platform-by-platform ROI analysis with recommended spend shift and projected impact on ROAS" },
      { ask: "Compare Instacart vs. Walmart Connect for our CPG brand", returns: "Side-by-side comparison on reach, cost efficiency, targeting capabilities, and measurement quality" },
    ],
  },
  {
    id: 3,
    slug: "travel-retail-intelligence",
    name: "Travel Retail Intelligence",
    author: "RetailEdge",
    description: "Airport and cruise retail analytics — passenger flow modeling, dwell time optimization, duty-free pricing benchmarks.",
    long_description: "Claude becomes a travel retail analyst. Ask about airport retail performance, passenger conversion, or duty-free pricing and get analysis calibrated to global travel retail benchmarks.",
    repo_url: null,
    installs: 290,
    stars: 38,
    badge: "Popular",
    industries: ["travel", "retail"],
    functions: ["operations", "data"],
    use_cases: [
      { ask: "What's driving the conversion drop in Terminal 2 duty-free?", returns: "Passenger flow analysis with dwell time breakdown, category performance comparison, and layout optimisation suggestions" },
      { ask: "Benchmark our duty-free pricing against Singapore Changi", returns: "Category-by-category price comparison with margin analysis and competitive positioning recommendations" },
      { ask: "Model the revenue impact of the new cruise terminal", returns: "Passenger volume projection, spend-per-head estimates by category, and staffing model for peak seasons" },
    ],
  },
  {
    id: 4,
    slug: "vendor-scorecard-builder",
    name: "Vendor Scorecard Builder",
    author: "ProcureAI",
    description: "Automated vendor performance scoring — KPI tracking, contract compliance monitoring, renewal risk assessment.",
    long_description: "This skill turns Claude into a procurement analyst. When you ask about vendor performance, supplier evaluation, or contract reviews, Claude applies a structured scoring methodology and produces formatted scorecards.",
    repo_url: "https://github.com/procureai/vendor-scorecard",
    installs: 410,
    stars: 56,
    badge: null,
    industries: ["retail", "cpg", "financial", "industrials"],
    functions: ["procurement", "operations"],
    use_cases: [
      { ask: "Review our top 5 packaging suppliers from last quarter", returns: "Ranked scorecard with scores on delivery, quality, cost, responsiveness — and a renew / renegotiate / replace recommendation for each" },
      { ask: "Should we renew the CartonKing contract?", returns: "Vendor deep-dive with trend analysis, risk flags, and a side-by-side comparison against alternatives in your portfolio" },
      { ask: "Evaluate this new supplier proposal", returns: "Prospect scored against your existing vendor benchmarks, with a gap analysis and onboarding risk assessment" },
      { ask: "Which categories have single-source risk?", returns: "Portfolio heat map showing concentration risk, suppliers below threshold, and suggested diversification targets" },
    ],
  },
  {
    id: 5,
    slug: "data-monetization-framework",
    name: "Data Monetization Framework",
    author: "DataCommerce",
    description: "Structure and price data products for B2B commerce. Data valuation models, privacy compliance, and revenue projections.",
    long_description: "Claude helps you build a data monetization strategy. Ask about data product design, pricing models, or privacy compliance and get structured frameworks for turning first-party data into revenue.",
    repo_url: null,
    installs: 520,
    stars: 89,
    badge: "Trending",
    industries: ["retail", "financial", "tmt"],
    functions: ["data", "strategy", "finance"],
    use_cases: [
      { ask: "What first-party data assets could we monetize?", returns: "Data asset inventory with valuation estimates, buyer personas, and privacy risk assessment for each" },
      { ask: "Price our retail analytics data product for FMCG brands", returns: "Pricing model with tier structure, competitive benchmarks, and projected revenue at different adoption rates" },
      { ask: "Is our data sharing agreement GDPR compliant?", returns: "Clause-by-clause compliance review with risk flags, recommended amendments, and a compliant template" },
    ],
  },
  {
    id: 6,
    slug: "fmcg-category-manager",
    name: "FMCG Category Manager",
    author: "ShelfLogic",
    description: "Category management for FMCG — space-to-sales analysis, planogram optimization, promotional lift measurement.",
    long_description: "Claude becomes a category management specialist. Ask about shelf performance, planogram efficiency, or promotional ROI and get analysis grounded in FMCG best practices.",
    repo_url: null,
    installs: 195,
    stars: 31,
    badge: null,
    industries: ["cpg", "retail"],
    functions: ["marketing", "operations"],
    use_cases: [
      { ask: "Analyse the space-to-sales ratio for our beverage category", returns: "SKU-level analysis showing over/under-spaced products with recommended planogram adjustments and projected sales lift" },
      { ask: "Did last month's promotion on snacks actually work?", returns: "Promotional lift analysis with baseline comparison, cannibalisation effects, and incremental margin calculation" },
      { ask: "Optimise our planogram for the new store format", returns: "Category flow recommendation with fixture allocation, adjacency logic, and expected conversion impact" },
    ],
  },
  {
    id: 7,
    slug: "financial-due-diligence",
    name: "Financial Due Diligence",
    author: "DealRoom",
    description: "M&A due diligence workflows — financial model auditing, red flag detection, deal comparison frameworks.",
    long_description: "Claude works as a due diligence analyst. Upload financial models or deal documents and get structured analysis — red flags, normalisation adjustments, and deal comparison frameworks.",
    repo_url: null,
    installs: 380,
    stars: 72,
    badge: null,
    industries: ["financial", "privatecapital"],
    functions: ["ma", "finance", "risk"],
    use_cases: [
      { ask: "Review this financial model for red flags", returns: "Line-by-line audit with flagged assumptions, circular references, formula errors, and sensitivity analysis on key drivers" },
      { ask: "Compare these three acquisition targets", returns: "Normalised comparison table with EV/EBITDA, revenue quality scores, integration risk, and ranked recommendation" },
      { ask: "What quality of earnings adjustments should we make?", returns: "Adjustment schedule with one-time items, non-recurring revenue, related party transactions, and restated EBITDA" },
    ],
  },
  {
    id: 8,
    slug: "pricing-intelligence-suite",
    name: "Pricing Intelligence Suite",
    author: "PriceWise",
    description: "Dynamic pricing analytics — competitor monitoring, elasticity modeling, markdown optimization with real-time signals.",
    long_description: "Claude becomes a pricing analyst. Ask about competitive pricing, demand elasticity, or markdown strategy and get data-driven recommendations calibrated to your market.",
    repo_url: null,
    installs: 310,
    stars: 45,
    badge: "New",
    industries: ["retail", "travel", "cpg"],
    functions: ["marketing", "data", "finance"],
    use_cases: [
      { ask: "Are we priced competitively in the premium skincare category?", returns: "Competitive price map with positioning analysis, price gap assessment, and recommended adjustments by SKU" },
      { ask: "Model the impact of a 10% price increase on our top 20 SKUs", returns: "Elasticity-based volume forecast, margin impact analysis, and a phased implementation recommendation" },
      { ask: "Optimise our end-of-season markdown schedule", returns: "Week-by-week markdown cadence with projected sell-through rates, margin preservation targets, and clearance timeline" },
    ],
  },
  {
    id: 9,
    slug: "workforce-planning-modeler",
    name: "Workforce Planning Modeler",
    author: "TalentOps",
    description: "Scenario-based workforce planning — headcount optimization, skills gap analysis, attrition modeling.",
    long_description: "Claude helps with workforce planning. Ask about headcount scenarios, skills gaps, or attrition risk and get structured models with financial impact analysis.",
    repo_url: null,
    installs: 240,
    stars: 33,
    badge: null,
    industries: ["retail", "financial", "healthcare", "tmt"],
    functions: ["people", "strategy", "finance"],
    use_cases: [
      { ask: "Model three headcount scenarios for our 2027 budget", returns: "Side-by-side comparison of conservative, baseline, and growth scenarios with cost projections and capability gaps for each" },
      { ask: "Where are our biggest skills gaps for the AI transformation?", returns: "Skills heat map across departments with gap severity, build-vs-buy recommendation, and training investment estimate" },
      { ask: "Predict attrition risk for our engineering team", returns: "Risk-scored employee segments with leading indicators, retention cost analysis, and targeted intervention plan" },
    ],
  },
  {
    id: 10,
    slug: "regulatory-compliance-tracker",
    name: "Regulatory Compliance Tracker",
    author: "GovReady",
    description: "Regulatory change monitoring across jurisdictions — impact assessment for GDPR, FDA, SEC, and sector frameworks.",
    long_description: "Claude monitors regulatory changes relevant to your industry. Ask about compliance impact, upcoming deadlines, or cross-jurisdiction differences and get structured assessments.",
    repo_url: null,
    installs: 350,
    stars: 61,
    badge: null,
    industries: ["financial", "healthcare", "energy"],
    functions: ["risk", "operations"],
    use_cases: [
      { ask: "What regulatory changes affect our EU operations this quarter?", returns: "Timeline of upcoming regulatory deadlines with impact assessment, required actions, and responsible teams" },
      { ask: "Compare GDPR vs. CCPA requirements for our data practices", returns: "Side-by-side compliance matrix with gap analysis, risk areas, and recommended policy updates" },
      { ask: "Assess the impact of the new FDA guidance on our product line", returns: "Product-by-product impact assessment with compliance timeline, cost estimate, and prioritised action plan" },
    ],
  },
  {
    id: 11,
    slug: "procurement-spend-analyzer",
    name: "Procurement Spend Analyzer",
    author: "Chip Alexandru / Zinit",
    description: "Apply McKinsey/AT Kearney-grade savings levers to raw spend data and produce a prioritized pipeline with eRFx-ready sourcing actions.",
    long_description: "Ingests procurement spend data, profiles transactions across suppliers and categories, then systematically applies savings levers: cross-site price harmonization, category consolidation, contract leakage detection, sole-source risk flagging, and design-to-value analysis. Produces two coordinated outputs: a detailed Excel workbook for analytical depth and an HTML executive report for stakeholder sharing.",
    repo_url: null,
    installs: 0,
    stars: 0,
    badge: "New",
    version: "vFF2",
    category: "Procurement & Sourcing",
    industries: ["cpg", "retail", "industrials", "chemicals", "energy"],
    functions: ["procurement", "operations", "finance"],
    use_cases: [
      { ask: "Analyze this spend data and find savings", returns: "Prioritized savings pipeline, category breakdowns, risk flags, and sourcing recommendations across both deliverables" },
      { ask: "Where are our biggest price inconsistencies?", returns: "Item-by-item comparison of prices paid across sites, flagging spreads above 10% with savings per line" },
      { ask: "Which categories should we take to market?", returns: "RFx-ready categories ranked by estimated savings, ease of execution, and recommended sourcing action" },
    ],
    inputs: [
      { label: "Spend data", detail: "CSV or Excel with PO, supplier, description, quantity, unit price, category", required: true },
      { label: "Contract register", detail: "Contracted prices, expiry dates, rebate terms — upgrades leakage analysis from hypothesis to quantified", required: false },
      { label: "Cost center / GL mapping", detail: "For departmental allocation", required: false },
      { label: "Should-cost references", detail: "BOM or cost benchmarks for manufactured parts", required: false },
    ],
    outputs: [
      { label: "Excel workbook", detail: "10-sheet analytical workbook — summary pipeline, spend overview, price harmonization detail, supplier analysis, contract leakage, sole-source risk, quick wins, savings pipeline, design-to-value & should-cost, raw data" },
      { label: "HTML executive report", detail: "Interactive dashboard with KPI cards, animated charts, savings pipeline, eRFx opportunity table, risk cards, should-cost models, and a share-with-colleague button" },
    ],
    how_it_works: [
      { title: "Cross-site price comparison", detail: "Finds items where different sites pay different prices for the same thing, and calculates what you'd save by paying the lowest price everywhere. Only counts the actual overcharge per transaction." },
      { title: "Category-specific savings rates", detail: "Uses consulting benchmarks to set realistic savings targets per category (e.g., 12% for MRO parts, 8% for logistics) instead of applying a single flat rate across all spend." },
      { title: "Contract leakage detection", detail: "Without a contract file: identifies off-contract purchases and one-off buys as areas to investigate. With a contract file: calculates exactly how much you're overpaying vs. contracted rates, spending on expired contracts, or leaving on the table in volume rebates." },
      { title: "No double-counting", detail: "Related savings opportunities are grouped so the total pipeline reflects what you can actually capture — overlapping items aren't counted twice." },
      { title: "Should-cost modeling", detail: "For high-spend, high-volume items, builds a cost model breaking down material, labor, overhead, and margin to show what a part should cost — giving your sourcing team a data-backed starting point for negotiation." },
    ],
    tools: "Standalone — works entirely from uploaded files with no external integrations required. Optionally links to Zinit for launching eRFx and eAuction events directly from the report.",
    skills_summary: "Single invocable skill that runs the full engagement end-to-end — from data ingestion through analysis to dual-deliverable output.",
  },
];
